### ISSUE TITLE
a script that generates tiles and a mappack from pictures

### ISSUE THREAD

**Issue by squadwon** [Stabyourself/mari0#10]
I'm not too sharp with lua, but learning.  I could, however, easily do this in node, but wouldn't mind trying to take a stab at it in lua.  It actually wouldn't be too hard the more I think about it.  Tiles are a specific size, so in essence you'd simply break a huge picture up into specified size sprites, then create a configuration based off their location.
Later you could edit the map, removing any unwanted tiles, and insert your own.

**Comment by Stabyourself** [comment]
Hey, sorry for the very late reply, I don't use github much.
There's no real plans to update Mari0 (1.6) with any features. Anything like this would fit better into the sequel, which is not in open development, sorry.
