### ISSUE TITLE
Supporting only 0.8.0 bites.

### ISSUE THREAD

**Issue by dotnetCarpenter** [Stabyourself/mari0#12]
OS: Ubuntu xenial 16.04.1 LTS

I can't find the 0.8.0 version of LÖVE. It's not here: https://love2d.org/builds/ and not in the main Ubuntu PPA:
```
sudo apt install love=0.8.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '0.8.0' for 'love' was not found
```

The current LÖVE version in Ubuntu's PPA is 0.9.1.
```
love/xenial 0.9.1-3ubuntu1 amd64
  2D game development framework based on Lua and OpenGL
```
Which fails with the following (also reported [here](http://forum.stabyourself.net/viewtopic.php?f=10&t=4076)):
```
love mari0_1.6.love 
This game was made for a different version of LÖVE.
It may not be not be compatible with the running version (0.9.1).
Error: main.lua:13: attempt to call field 'enumerate' (a nil value)
stack traceback:
	main.lua:13: in function 'load'
	[string "boot.lua"]:406: in function <[string "boot.lua"]:399>
	[C]: in function 'xpcall'
```

@Stabyourself Do you accept Pull Request for mari0?

**Comment by Stabyourself** [comment]
The current master branch has been updated to work on LÖVE 0.10.1, and I just quickly tried it on 0.10.2 (the current version) and it also worked.

**Comment by dotnetCarpenter** [comment]
@Stabyourself Thanks - I'll give it a try.

**Comment by dotnetCarpenter** [comment]
OS: Ubuntu xenial 16.04.1 LTS
LÖVE: LOVE 0.10.2 (Super Toast)

I manage to get it working by doing the following:
```
sudo add-apt-repository ppa:bartbes/love-stable
sudo apt-get update
sudo apt install love=0.10.2ppa1
git clone --depth=1 https://github.com/Stabyourself/mari0.git
cd mari0/
touch .gitattributes
nano .gitattributes
```
In nano I wrote:
```
"_DO NOT INCLUDE" export-ignore
```
Then I saved the file (Ctrl+x):
```
git archive --format=zip -o mari0.love -9 HEAD
zip -T mari0.love
mv mari0.love ..
cd ..
love mari0.love
```

The result was that I could play the game although mario has some issues turning in the _right_ direction.

```
love mari0.love 
Custom tileset loaded in: 1e-05
false
Custom tileset loaded in: 1e-05
false
Loading mappacks/smb/1-1.txt
Loading mappacks/smb/1-1_1.txt
Loading mappacks/smb/1-1.txt
Loading mappacks/smb/1-2.txt
Loading mappacks/smb/1-2_1.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by dotnetCarpenter** [comment]
Available LÖVE packages for Ubuntu: https://launchpad.net/~bartbes/+archive/ubuntu/love-stable
