### ISSUE TITLE
Using PS3 controller with Mari0 fails on getAxis to replace the mouse.

### ISSUE THREAD

**Issue by hprudent** [Stabyourself/mari0#14]
To use the default commands (Pads and Buttons) everything works.

Only the Axis to replace mouse displays the bellow error.

```
Error

mario.lua:1030: attempt to call field 'getAxis' (a nil value)

Traceback

mario.lua:1030: in function 'updateangle'
mario.lua:941: in function 'update'
game.lua:447: in function 'game_update'
main.lua:798: in function 'update'
[C]: in function 'xpcall'
```

**Comment by Noahkiq** [comment]
All circle sticks are broken in the newer versions. (v1.6.1, master, & SE) -- You'd have to use an older version or a different LOVE 0.10 port if you want circle stick support. (I think https://github.com/radgeRayden/future-mari0 supports circle sticks, but also has a few other misc. issues...)
