### ISSUE TITLE
Quick question cause reading long texts like licenses hurt my eyes.

### ISSUE THREAD

**Issue by JacobSinclair** [Stabyourself/mari0#16]
With the licence that Mari0 SE is under, can I distribute a mod stand alone and can I make it closed source? (I will probably still make it open-source but I wana know what freedoms I have). Also, could I distribute the mod on gamejolt as its own game?

**Comment by Stabyourself** [comment]
Sure thing.

**Comment by JacobSinclair** [comment]
yay. its really just a mod loader so you don't need to download a new copy of the game for every mod you download, and it adds a simpler API for modding.


// Off topic

Is Mari0 still under development?

**Comment by Stabyourself** [comment]
Not since 2014, no.
