### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Stabyourself/mari0#22]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/mari0), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):

    # Install the snap #
    sudo snap install mari0

    # Connect the snap to optional security confinement interfaces #
    ## For allowing the game to use joystick ##
    sudo snap connect mari0:joystick
    
    # Launch the application #
    mari0

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/mari0-snap/blob/master/snap/snapcraft.yaml), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by Stabyourself** [comment]
Hey, so as far as I understand, this is some kind of package alternative? Kinda like docker?
I like the idea, but I don't think I want any specific build/snap tools inside the repo. The repo itself is a .love package.
I'm happy that you have built one and you can of course continue to do so, it's just not something I can see myself doing.

**Comment by Lin-Buo-Ren** [comment]
> so as far as I understand, this is some kind of package alternative?  Kinda like docker?

Yep.

> I'm happy that you have built one and you can of course continue to do so, it's just not something I can see myself doing.

That's fine, thanks for your consideration.

That's totally fine

**Comment by keithbowes** [comment]
Snap is universal, for Ubuntu only.  You're much better off with AppImage, which doesn't require anything special, other than making sure that the executable bit is set, and is more than just Canonical's attempt to imitate Windows' Program Files structure.
