### ISSUE TITLE
How to enable netplay in game?

### ISSUE THREAD

**Issue by BlueBerrySans365** [Stabyourself/mari0#29]
Hello, i tried to edit some scripts and enable netplay and after all i stopped on `onlinemenu.lua:47: attempt to perform arithmetic on global 'runanimationtimer' (a nil value)`

(If what, i copied some files (like client.lua, server.lua etc.) from older versions and made another option in menu.lua.)

Why did you cancelled netplay and how it can be restored?
Using LOVE 11.3 (Mysterious Mysteries)

**Comment by Stabyourself** [comment]
hey,

I cancelled netplay because it would've been too much work, and it can't be restored because it isn't done.
