### ISSUE TITLE
Formal request to take over development

### ISSUE THREAD

**Issue by HACKhalo2** [Stabyourself/mari0#4]
Heya. I ran into this game again two days ago via Reddit and /r/gamegrumps, and (mostly) ported 1.6 to use Love 0.9.1. I'm wondering, since there has been no commits or anything done in two years if I can take over development as a hobby project.

**Comment by remram44** [comment]
0.9.1 support would be good :cry:

**Comment by mckaygerhard** [comment]
ping? any update?
