### ISSUE TITLE
Online mode

### ISSUE THREAD

**Issue by dud225** [Stabyourself/mari0#40]
Hello

A online mode is implemented:
![Capture d’écran de 2023-04-03 06-10-33](https://user-images.githubusercontent.com/17550475/229409582-fe98f80f-c8bb-424b-9c77-2d91e307438a.png)

but this menu entry doesn't show up on my computer.

There are references in the code but I'm not sure there is any way to reach it (there is no `gamestate = onlinemenu`)

**Comment by qixils** [comment]
Online play functionality is from the cancelled Special Edition update which you will not find in this repository.

**Comment by dud225** [comment]
Too bad. Thanks I wasn't aware of this story.
