### ISSUE TITLE
Save data handled incorrectly

### ISSUE THREAD

**Issue by M0REKZ** [Stabyourself/mari0#45]
OS: macOS Ventura 13.4.1 (c) 
Game Version: CI build (master)

When i modify options in-game, exit and re-open mari0, the changes wont be saved, so i decided to take a look to "Application Support" folder and noticed that the game created 2 new folders: LOVE and mari0, and for some reason it saves data on mari0 folder but will load from LOVE folder, so newer modified options will never be read.

**Comment by qixils** [comment]
I suppose this is likely caused by https://github.com/Stabyourself/mari0/commit/f99317f1948bc7dc288c650e3f15107711a390ad but I'm not sure why, never experienced such issues myself during testing. Will investigate
