### ISSUE TITLE
Easy to use Makefile pack

### ISSUE THREAD

**Issue by district10** [Stabyourself/mari0#7]
I wrote a `Makefile` so that, packing all these `*.lua` files, images, sound flies to a `mari0.love` will be as simple as typing `make` in the shell.

On windows, you can also `make pack` to pack the standalone `mari0.exe`. (though you still need these dlls in `bin/love-0.10.1-win64` to run this executable.)

My fork: [district10/mari0: Mario + Portal game in LÖVE](https://github.com/district10/mari0).

**Comment by Stabyourself** [comment]
I'm not sure how necessary makefiles are for löve projects. 
There's a packer thing that also changes the icon properly, so if necessary I'll probably look at that.
