### ISSUE TITLE
Handle quad properties using specific declarations rather than by color

### ISSUE THREAD

**Issue by squadwon** [Stabyourself/mari0#8]
I uncovered that quads are currently configured by their color, it would be nice to be able to configure them using a more direct means, and without coding it.

**Comment by squadwon** [comment]
For map packs I did end up finding a means that _I think_ may be somewhat straightforward and easy.  The solution is based off of file name.  I've customized the sprite import handler to do this using multiple tiles.png files of sorts.  Default tiles that make quads do nothing (ie, a background tile) can simply be:

`mappacks/mappackname/tiles.png`
and to add tiles that configure quad properties:
`mappacks/mappackname/tiles/collision.png`
`mappacks/mappackname/tiles/invisible.png`
`mappacks/mappackname/tiles/collision-invisible-whatever-else-properties-it-has.png`

It isn't a perfect solution, but it is straightforward and easily compartmentalizes the sprites, even during level editing.  If there is interest I can open a pull request.  The tiles load in alphabetical order, and the name of the file is simply checked for the existence of any of the property names, so you could do something like this if you wanted to maintain order:
`mappacks/mappackname/tiles/0-collision.png`
`mappacks/mappackname/tiles/1-invisible.png`
`mappacks/mappackname/tiles/2-collision-invisible-whatever-else-properties-it-has.png`

**Comment by Stabyourself** [comment]
Hey, sorry for the very late reply, I don't use github much.
There's no real plans to update Mari0 (1.6) with any features. Anything like this would fit better into the sequel, which is not in open development, sorry.
